apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: openshift-config
stringData:
  htpasswd: |
{{- range .Values.users }}
    {{ .name }}:{{ .password | bcrypt }}
{{- end }}