apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
data:
  policy.csv: |
    g, system:cluster-admins, role:admin
    g, cluster-admins, role:admin
  policy.default: ''
  scopes: '[groups]'
  rbac.yaml: |
    {{- range .Values.teams }}
    # Grant {{ . }} admin access to the {{ . }} namespace
    p, role:{{ $.Values.role }}, applications, get, {{ . }}/*, allow
    p, role:{{ $.Values.role }}, applications, list, {{ . }}/*, allow
    p, role:{{ $.Values.role }}, applications, sync, {{ . }}/*, allow
    p, role:{{ $.Values.role }}, applications, create, {{ . }}/*, allow
    p, role:{{ $.Values.role }}, applications, delete, {{ . }}/*, allow
    g, {{ . }}, role:{{ $.Values.role }}
    {{- end }}
