{{- range .Values.teams }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ . }}
  namespace: {{ . }}
spec:
  hard:
    limits.cpu: "250m"
    limits.memory: "0.8Gi"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: {{ . }}
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 0.8Gi
---
{{- end }}