{{- range .Values.teams }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ . }}
  namespace: {{ . }}
spec:
  hard:
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: {{ . }}
spec:
  limits:
    - type: Container
      default:
        cpu: 4
        memory: 8Gi
---
{{- end }}