{{- range .Values.teams }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-admin-rolebinding
  namespace: {{ . }}
subjects:
  - kind: Group
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ . }}-sa
    namespace: {{ . }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}