apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: cluster-admin-dashboard
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  json: |
    {
      "dashboard": {
        "id": null,
        "title": "Cluster Admin Dashboard",
        "panels": [
          {
            "type": "graph",
            "title": "Total CPU Usage (by Node)",
            "targets": [
              {
                "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (node)"
              }
            ]
          },
          {
            "type": "graph",
            "title": "Total Memory Usage (by Node)",
            "targets": [
              {
                "expr": "sum(container_memory_working_set_bytes) by (node)"
              }
            ]
          }
        ]
      },
      "overwrite": true
    }
