apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: cluster-admin-dashboard
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      app: grafana
  json: |
    {
      "dashboard": {
        "title": "Cluster Admin Dashboard",
        "panels": [
          {
            "type": "graph",
            "title": "Cluster CPU Usage",
            "targets": [
              {
                "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))",
                "refId": "A"
              }
            ]
          },
          {
            "type": "graph",
            "title": "Cluster Memory Usage",
            "targets": [
              {
                "expr": "sum(container_memory_working_set_bytes)",
                "refId": "B"
              }
            ]
          },
          {
            "type": "graph",
            "title": "Total Pods",
            "targets": [
              {
                "expr": "count(kube_pod_info)",
                "refId": "C"
              }
            ]
          },
          {
            "type": "graph",
            "title": "User Created Resources",
            "targets": [
              {
                "expr": "count(kube_resourcequota{namespace!~\"^openshift.*\"})",
                "refId": "D"
              }
            ]
          }
        ],
        "overwrite": true
      },
      "overwrite": true
    }