apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  datasource:
    name: Prometheus
    type: prometheus
    url: "http://thanos-querier.openshift-monitoring.svc:9090"
    access: proxy
    isDefault: true
  instanceSelector:
    matchLabels:
      app: grafana