apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
  namespace: monitoring
spec:
  name: prometheus.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      url: http://thanos-querier.openshift-monitoring.svc:9091
      access: proxy
      isDefault: true