apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  serviceAccountName: grafana
  ingress:
    enabled: true
    hostname: grafana-service.apps.hashlama016-red-openshift.bsmch.net
  config:
    log:
      mode: "console"
      level: "info"
    security:
      admin_user: "admin"
      admin_password: "admin"

