apiVersion: integreatly.org/v1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  name: prometheus.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      url: http://thanos-querier.openshift-monitoring.svc:9091
      access: proxy
      isDefault: true
  instanceSelector:
    matchLabels:
      app: grafana
