apiVersion: integreatly.org/v1alpha1
kind: GrafanaDatasource
metadata:
  name: thanos-querier-datasource
  namespace: monitoring
spec:
  name: thanos-querier.yaml
  datasources:
    - name: Thanos Querier
      type: prometheus
      access: proxy
      # Using the internal service name and port from the built-in OpenShift Monitoring stack:
      url: http://thanos-querier.openshift-monitoring.svc:9091/api/v1
      isDefault: false
      editable: true
