apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  datasource:
    name: Prometheus
    type: prometheus
    url: "https://thanos-querier-openshift-monitoring.apps.hashlama016-red-openshift.bsmch.net/api"
    access: proxy
    isDefault: true
    jsonData:
      tlsSkipVerify: true
  instanceSelector:
    matchLabels:
      app: grafana