apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceAccountName: grafana
  ingress:
    enabled: true
  config:
    log:
      mode: "console"
      level: "info"
    security:
      admin_user: "admin"
      admin_password: "admin"
