apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: default
  labels:
    app: harbor-secret
    type: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"10.50.19.11":{"username":"admin","password":"Harbor12345"}}}'